### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cartal** [JSybrandt/MOLIERE#6]
Hi, 

I have been trying to install the MOLIERE pipeline in my local server, with little success. 

At first it was not finding the NetworkIt libraries, but I solved it somehow by running the git clone with the --recursive flag (maybe something add to the repo README?), but now I am having troubles with the installation (See attached screenshot).

Any ideas what I may be doing wrong?

Thanks! 

![screen shot 2018-05-15 at 10 59 50](https://user-images.githubusercontent.com/3297906/40050376-34c61042-582f-11e8-900a-9b2ea6a68f0e.png)

**Comment by JSybrandt** [comment]
Just did some tests and it looks like 5.4 should also work.
Additionally, the updated readme is up.

**Comment by JSybrandt** [comment]
Okay, thanks for letting me know.
I just pushed a change for the line from `{a, b, w}` to `rawEdge(a, b, w)` which should be far more compatible.
Let me know if you still have issues.
